services:
  - type: web
    name: tst-facil
    env: node
    region: oregon
    plan: free

    buildCommand: |
      echo "ğŸ› ï¸ Iniciando instalaÃ§Ã£o das dependÃªncias..."
      pnpm install --no-frozen-lockfile
      echo "ğŸ—ï¸ Gerando build do projeto..."
      pnpm run build

    startCommand: |
      echo "ğŸš€ Iniciando servidor Node..."
      pnpm run start

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

    autoDeploy: true
